name: demo-web CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "demo-web/**"           # kód aplikace
      - ".github/workflows/demo-web-ci.yml"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # kvůli commitu zpět do repa
      packages: write       # kvůli push do ghcr
      id-token: write       # do budoucna se hodí pro OIDC

    env:
      IMAGE_NAME: ghcr.io/huhlik-cz/demo-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./demo-web
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Update image tag in deployment manifest
        run: |
          TAG=${{ steps.vars.outputs.tag }}
          FILE="k8s/deployment.yaml"

          echo "Updating image tag in $FILE to ${TAG}"

          sed -i "s|\(ghcr.io/huhlik-cz/demo-web:\).*|\1${TAG}|" "$FILE"

          echo "Result:"
          grep "ghcr.io/huhlik-cz/demo-web" "$FILE"

      - name: Commit and push changes
        run: |
          TAG=${{ steps.vars.outputs.tag }}

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/demo-web/deployment.yaml

          if git diff --cached --quiet; then
            echo "No changes in deployment file, skipping commit."
            exit 0
          fi

          git commit -m "Deploy demo-app image ${TAG}"
          git push

